[tool.poetry]
name = "randlab-przetargowisko" 
version = "0.1.0"
description = "Randlab's przetargowisko project"
authors = ["bartosz.papinski00@gmail.com"]
readme = "README.md"
package-mode = false

[tool.poetry.dependencies]
python = "^3.10" 


[tool.poetry.group.dev.dependencies]
pre-commit = "^3.7.0"
ruff = "^0.4.5"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"