# Generated by Django 5.0.14 on 2025-07-30 13:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Tender",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=255, verbose_name="Nazwa przetargu"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="TenderEntry",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "position",
                    models.CharField(max_length=255, verbose_name="Stanowisko"),
                ),
                ("company", models.CharField(max_length=255, verbose_name="Firma")),
                (
                    "developer_price",
                    models.DecimalField(decimal_places=2, max_digits=12, verbose_name="Cena developera"),
                ),
                (
                    "margin",
                    models.DecimalField(decimal_places=2, max_digits=6, verbose_name="Marża"),
                ),
                (
                    "total_price",
                    models.DecimalField(decimal_places=2, max_digits=12, verbose_name="Cena całkowita"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "tender",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="entries",
                        to="tenders.tender",
                    ),
                ),
            ],
        ),
    ]
