# Generated by Django 5.0.14 on 2025-07-31 17:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tenders", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="tender",
            name="is_active",
            field=models.BooleanField(default=True, verbose_name="Is active"),
        ),
        migrations.AlterField(
            model_name="tender",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, verbose_name="Created at"),
        ),
        migrations.AlterField(
            model_name="tender",
            name="name",
            field=models.CharField(max_length=255, verbose_name="Tender name"),
        ),
        migrations.AlterField(
            model_name="tender",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, verbose_name="Updated at"),
        ),
        migrations.AlterField(
            model_name="tenderentry",
            name="company",
            field=models.CharField(max_length=255, verbose_name="Company"),
        ),
        migrations.AlterField(
            model_name="tenderentry",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, verbose_name="Created at"),
        ),
        migrations.AlterField(
            model_name="tenderentry",
            name="developer_price",
            field=models.DecimalField(
                decimal_places=2, max_digits=12, verbose_name="Developer price"
            ),
        ),
        migrations.AlterField(
            model_name="tenderentry",
            name="margin",
            field=models.DecimalField(
                decimal_places=2, max_digits=6, verbose_name="Margin (%)"
            ),
        ),
        migrations.AlterField(
            model_name="tenderentry",
            name="position",
            field=models.CharField(max_length=255, verbose_name="Position"),
        ),
        migrations.AlterField(
            model_name="tenderentry",
            name="tender",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="entries",
                to="tenders.tender",
                verbose_name="Tender",
            ),
        ),
        migrations.AlterField(
            model_name="tenderentry",
            name="total_price",
            field=models.DecimalField(
                decimal_places=2, max_digits=12, verbose_name="Total price"
            ),
        ),
        migrations.AlterField(
            model_name="tenderentry",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, verbose_name="Updated at"),
        ),
    ]
