# Generated by Django 5.0.14 on 2025-08-27 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tenders", "0002_tender_is_active_alter_tender_created_at_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="tender",
            name="client",
            field=models.CharField(
                default="Unknown", max_length=255, verbose_name="Client"
            ),
        ),
        migrations.AddField(
            model_name="tender",
            name="implementation_link",
            field=models.URLField(blank=True, default="", null=True),
        ),
        migrations.AddField(
            model_name="tender",
            name="status",
            field=models.CharField(
                choices=[
                    ("won", "Won"),
                    ("lost", "Lost"),
                    ("unresolved", "Unresolved"),
                ],
                default="unresolved",
                max_length=12,
                verbose_name="Status",
            ),
        ),
    ]
