# Generated by Django 5.0.14 on 2025-08-27 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tenders", "0003_tender_client_tender_implementation_link_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="tenderentry",
            name="description",
            field=models.TextField(blank=True, null=True, verbose_name="Description"),
        ),
    ]
