# Generated by Django 5.0.14 on 2025-09-01 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tenders", "0004_tenderentry_description"),
    ]

    operations = [
        migrations.AddField(
            model_name="tender",
            name="file",
            field=models.FileField(
                blank=True, null=True, upload_to="tender_files/"
            ),
        ),
    ]
