# Generated by Django 5.0.14 on 2025-09-01 13:15

import django.db.models.deletion
import tenders.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tenders", "0005_tender_file"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="tender",
            name="file",
        ),
        migrations.CreateModel(
            name="UploadedFile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "file",
                    models.FileField(
                        upload_to=tenders.models.tender_file_upload_to
                    ),
                ),
                ("uploaded_at", models.DateTimeField(auto_now_add=True)),
                (
                    "tender",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="uploaded_files",
                        to="tenders.tender",
                    ),
                ),
            ],
        ),
    ]
