name: Lint Python Code

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  lint:
    name: Run flake8, black and isort
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install flake8 black isort

      - name: Run flake8
        run: flake8 . --max-line-length=79 --extend-ignore=E501

      - name: Run black (check only)
        run: black . --check --line-length=79

      - name: Run isort (check only)
        run: isort . --check-only --profile=black --line-length=79